namespace PascalCompiler
{
    public static partial class Constants
    {
        public enum Symbol
        {
            Do = 54,
            If = 56,
            In = 22,
            Of = 8,
            Or = 23,
            To = 55,
            And = 24,
            Div = 25,
            End = 13,
            For = 26,
            Mod = 27,
            Nil = 89,
            Not = 28,
            Set = 29,
            Var = 30,
            Case = 31,
            Else = 32,
            File = 57,
            Goto = 33,
            Only = 90,
            Then = 52,
            Type = 34,
            Unit = 35,
            Uses = 36,
            With = 37,
            Array = 38,
            Begin = 17,
            Const = 39,
            Label = 40,
            Until = 53,
            While = 41,
            DownTo = 55,
            Export = 91,
            Import = 92,
            Module = 93,
            Packed = 42,
            Record = 43,
            Repeat = 44,
            Vector = 45,
            String = 46,
            Forward = 47,
            Process = 48,
            Program = 3,
            Segment = 49,
            Function = 77,
            Separate = 78,
            Interface = 79,
            Procedure = 80,
            Qualified = 94,
            Implementation = 81,

            Asterisk = 21,
            Slash = 60,
            Equals = 16,
            Comma = 20,
            Semicolon = 14,
            Colon = 5,
            Point = 61,
            Caret = 62,
            LeftRoundBracket = 9,
            RightRoundBracket = 4,
            LeftSquareBracket = 11,
            RightSquareBracket = 12,
            LeftCurlyBracket = 63,
            RightCurlyBracket = 64,
            Less = 65,
            Greater = 66,
            LessOrEqual = 67,
            GreaterOrEqual = 68,
            NotEqual = 69,
            Plus = 70,
            Minus = 71,
            LeftComment = 72,
            RightComment = 73,
            Assign = 51,
            TwoPoints = 74,
            Ident = 2,
            FloatConstant = 82,
            IntConstant = 15,
            CharConstant = 83,
            StringConstant = 84,
            EndOfFile = 253,
            EndOfLine = 88,
            False = 0,
            True = 1,
            Comment = 254,
        }
    }
}
